### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Vincent392**
Change latest video

### CODE REVIEW

**Comment by NexTre-dev** [comment]
does a page for the new video exist yet?

**Comment by Vincent392** [comment]
> does a page for the new video exist yet?

Yeah because its attachment_b849.avi

**Comment by Vincent392** [comment]
> > does a page for the new video exist yet?
> 
> Yeah because its attachment_b849.avi

And I'm sorry for being a bit late for the reply.

**Comment by doogo809** [comment]
You guys should implement this pull request

**Comment by Vincent392** [comment]
> You guys should implement this pull request

Yep

**Pull request merged**
